apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - nodePort: 30011
    port: 80
  selector:
    app: nginx-app
    type: front-end
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app
    type: front-end
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app
      type: front-end
  template:
    metadata:
      labels:
        app: nginx-app
        type: front-end
    spec:
      containers:
      - image: nginx:latest
        name: nginx-container
